# This is the autograder ((https://github.com/phpeterson-usf/autograder/)) 
# config file. The only thing we need for GGL is tests_path below

[Canvas]
# host_name = "usfca.test.instructure.com or canvas.instructure.com"
# access_token = "your access token here"
# course_name = "e.g. Computer Architecture - 01 (Spring 2022)"

[CanvasMapper]
# map_path = "your CSV mapping file here"
# github_col_name = "GitHub"
# login_col_name = "SIS Login ID"

[Config]
# students = []

[Git]
# org = "your GitHub Classroom org here"
# credentials = "ssh"

[Github]
# host_name = "api.github.com"
# access_token = "your access token here"

[Test]
tests_path = "./tests"
# digital_path = "~/Digital/Digital.jar"
